# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Menglong Guo
email: m.guo@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  My name is Menglong Guo and this is my website!
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://menglongguo.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/website" # the subpath of your site, e.g. /blog
theme: jekyll-theme-hacker
# source: .

# Analytics
analytics:
  provider               : google-universal # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : G-9MRBRC7QDR
    anonymize_ip         : # true, false (default)

collections:
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      latex: no
      stlwv2_models: no
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown
# theme: minima

gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
